import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import MessengerCustomerChat from 'react-messenger-customer-chat';
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <MessengerCustomerChat
    pageId="1724189954480599"
    appId="642497026793135"
  />,

    </div>
  )
}

